/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "main.h"

#include "DIALOG.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_BUTTON_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_1    (GUI_ID_USER + 0x02)

#define ID_TEXT_0    (GUI_ID_USER + 0x05)
#define ID_TEXT_1    (GUI_ID_USER + 0x06)
#define ID_TEXT_2    (GUI_ID_USER + 0x07)
#define ID_TEXT_3    (GUI_ID_USER + 0x08)

#define ID_TEXT_4    (GUI_ID_USER + 0x09)
#define ID_TEXT_5    (GUI_ID_USER + 0x0A)
#define ID_TEXT_6    (GUI_ID_USER + 0x0B)
#define ID_TEXT_7    (GUI_ID_USER + 0x0C)
#define ID_TEXT_8    (GUI_ID_USER + 0x0D)
#define ID_TEXT_9    (GUI_ID_USER + 0x0E)
#define ID_TEXT_10    (GUI_ID_USER + 0x0F)
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 320, 240, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 10, 190, 80, 40, 0, 0x0, 10 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 230, 190, 80, 40, 0, 0x0, 10 },
  { TEXT_CreateIndirect, "", ID_TEXT_0, 0, 15, 320, 80, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_1, 250, 7, 80, 80, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_2, 0, 0, 240, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_3, 240, 0, 80, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_4, 1,   101, 158, 38, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_5, 161, 101, 158, 38, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_6, 1, 141, 158, 38, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_7, 161, 141, 158, 38, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_8, 100, 190, 40, 40, 0, 0x0, 0 },  
  { TEXT_CreateIndirect, "", ID_TEXT_9, 140, 190, 40, 40, 0, 0x0, 0 },  
  { TEXT_CreateIndirect, "", ID_TEXT_10, 180, 190, 40, 40, 0, 0x0, 0 },  
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
WM_HWIN ui_main_hWin = NULL;
 
static void refresh_page()
{
    WM_HWIN hItem;
    char tmp_str[40] = {0};
    int i = 0;
//    GUI_Clear();

    sprintf(tmp_str,"%02d : %02d",sensor_data_lcd.hour ,sensor_data_lcd.min);
    hItem = WM_GetDialogItem(ui_main_hWin, ID_TEXT_0);
    TEXT_SetText(hItem,tmp_str);
    TEXT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_BOTTOM);
    TEXT_SetFont(hItem, &GUI_Font_micro_64);
    TEXT_SetBkColor(hItem,GUI_WHITE);
    
    sprintf(tmp_str,"%02d",sensor_data_lcd.sec);
    hItem = WM_GetDialogItem(ui_main_hWin, ID_TEXT_1);
    TEXT_SetText(hItem,tmp_str);
    TEXT_SetTextAlign(hItem, TEXT_CF_LEFT   | TEXT_CF_BOTTOM);
    TEXT_SetFont(hItem, &GUI_Font32_ASCII);
    TEXT_SetBkColor(hItem,GUI_WHITE);
    
    sprintf(tmp_str," %02d-%02d-%02d",sensor_data_lcd.year,sensor_data_lcd.month,sensor_data_lcd.date);
    hItem = WM_GetDialogItem(ui_main_hWin, ID_TEXT_2);
    TEXT_SetText(hItem,tmp_str);
    TEXT_SetTextAlign(hItem, TEXT_CF_LEFT   | TEXT_CF_VCENTER );
    TEXT_SetFont(hItem, &GUI_Font32_ASCII);
    TEXT_SetBkColor(hItem,GUI_LIGHTBLUE);
    
 
    hItem = WM_GetDialogItem(ui_main_hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, &GUI_Font_micro_32);
    switch(sensor_data_lcd.week)
    {
      case 1: TEXT_SetText(hItem, "星期一 ");
        break;
      case 2: TEXT_SetText(hItem, "星期二 ");
        break;
      case 3: TEXT_SetText(hItem, "星期三 ");
        break;
      case 4: TEXT_SetText(hItem, "星期四 ");
        break;
      case 5: TEXT_SetText(hItem, "星期五 ");
        break;
      case 6: TEXT_SetText(hItem, "星期六 ");
        break;
      case 7: TEXT_SetText(hItem, "星期日 ");
        break;
    }
    TEXT_SetTextAlign(hItem, TEXT_CF_LEFT   | TEXT_CF_VCENTER );
    TEXT_SetBkColor(hItem,GUI_LIGHTBLUE);
    
    
    sprintf(tmp_str,"CO2:%dppm",sensor_data_lcd.co2);
    hItem = WM_GetDialogItem(ui_main_hWin, ID_TEXT_6);
    TEXT_SetText(hItem,tmp_str);
    TEXT_SetTextAlign(hItem, TEXT_CF_LEFT   | TEXT_CF_VCENTER );
    TEXT_SetFont(hItem, &GUI_Font_micro_32);
    if(sensor_data_lcd.co2 < 450){
      TEXT_SetBkColor(hItem,GUI_GREEN);
    }else if((sensor_data_lcd.co2 < 1000)){
      TEXT_SetBkColor(hItem,GUI_YELLOW);
    }else{
      TEXT_SetBkColor(hItem,GUI_RED);
    }
    
    sprintf(tmp_str,"温度:%d℃ ",sensor_data_lcd.temp);
    hItem = WM_GetDialogItem(ui_main_hWin, ID_TEXT_4);
    TEXT_SetText(hItem,tmp_str);
    TEXT_SetTextAlign(hItem, TEXT_CF_LEFT   | TEXT_CF_VCENTER );
    TEXT_SetFont(hItem, &GUI_Font_micro_32);
    i = 23 - sensor_data_lcd.temp;
    i = abs(i);
    if(i < 4){
      TEXT_SetBkColor(hItem,GUI_GREEN);
    }else if((i < 8)){
      TEXT_SetBkColor(hItem,GUI_YELLOW);
    }else{
      TEXT_SetBkColor(hItem,GUI_RED);
    }
    
    sprintf(tmp_str,"甲醛:%dppd ",sensor_data_lcd.tvoc);
    hItem = WM_GetDialogItem(ui_main_hWin, ID_TEXT_7);
    TEXT_SetText(hItem,tmp_str);
    TEXT_SetTextAlign(hItem, TEXT_CF_LEFT   | TEXT_CF_VCENTER );
    TEXT_SetFont(hItem, &GUI_Font_micro_32);
    TEXT_SetBkColor(hItem,GUI_YELLOW);
    if(sensor_data_lcd.tvoc < 20){
      TEXT_SetBkColor(hItem,GUI_GREEN);
    }else if((sensor_data_lcd.tvoc < 50)){
      TEXT_SetBkColor(hItem,GUI_YELLOW);
    }else{
      TEXT_SetBkColor(hItem,GUI_RED);
    }

    
    sprintf(tmp_str,"湿度:%dppm ",sensor_data_lcd.humi);
    hItem = WM_GetDialogItem(ui_main_hWin, ID_TEXT_5);
    TEXT_SetText(hItem,tmp_str);
    TEXT_SetTextAlign(hItem, TEXT_CF_LEFT   | TEXT_CF_VCENTER );
    TEXT_SetFont(hItem, &GUI_Font_micro_32);
    TEXT_SetBkColor(hItem,GUI_YELLOW);
    i = 50 - sensor_data_lcd.humi;
    i = abs(i);
    if(i < 20){
      TEXT_SetBkColor(hItem,GUI_GREEN);
    }else if((i < 30)){
      TEXT_SetBkColor(hItem,GUI_YELLOW);
    }else{
      TEXT_SetBkColor(hItem,GUI_RED);
    }

    
    hItem = WM_GetDialogItem(ui_main_hWin, ID_TEXT_8);
    TEXT_SetText(hItem," 一般 "); // 
    TEXT_SetTextAlign(hItem, TEXT_CF_HCENTER|TEXT_CF_VCENTER );
    TEXT_SetFont(hItem, &GUI_Font_micro_25);
    TEXT_SetBkColor(hItem,GUI_INVALID_COLOR);
    TEXT_SetTextColor(hItem,GUI_YELLOW); 
      
    hItem = WM_GetDialogItem(ui_main_hWin, ID_TEXT_9);
    TEXT_SetText(hItem," 很好 "); // 
    TEXT_SetTextAlign(hItem, TEXT_CF_HCENTER|TEXT_CF_VCENTER );
    TEXT_SetFont(hItem, &GUI_Font_micro_25);
    TEXT_SetBkColor(hItem,GUI_INVALID_COLOR);
    TEXT_SetTextColor(hItem,GUI_GREEN);
      
    hItem = WM_GetDialogItem(ui_main_hWin, ID_TEXT_10);
    TEXT_SetText(hItem," 很差 "); // 
    TEXT_SetTextAlign(hItem, TEXT_CF_HCENTER|TEXT_CF_VCENTER );
    TEXT_SetFont(hItem, &GUI_Font_micro_25);
    TEXT_SetBkColor(hItem,GUI_INVALID_COLOR);
    TEXT_SetTextColor(hItem,GUI_RED); 

    data_set_lcd.year = sensor_data_lcd.year;
    data_set_lcd.month = sensor_data_lcd.month;
    data_set_lcd.date = sensor_data_lcd.date;
    data_set_lcd.hour = sensor_data_lcd.hour;
    data_set_lcd.min = sensor_data_lcd.min;
    data_set_lcd.week = sensor_data_lcd.week;
}
// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_TIMER:
    if(xQueueReceive(ParaSensorQue, &sensor_data_lcd, 0) == pdTRUE){
      refresh_page();

    }
    
    WM_RestartTimer(pMsg->Data.v, 500);
    break;
  case WM_PAINT:  
      //TEXT_SetBkColor
    GUI_SetColor(GUI_BLACK);
    GUI_DrawHLine(100,0,320);
    GUI_DrawHLine(140,0,320);
    GUI_DrawHLine(180,0,320);
    
    GUI_DrawVLine(0,100,180);
    GUI_DrawVLine(160,100,180);
    GUI_DrawVLine(319,100,180);
    refresh_page();
    break;
  case WM_INIT_DIALOG:
    
    hItem= WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    button_user_skin_set(hItem,"参数",NULL,0);

    hItem= WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    button_user_skin_set(hItem,"时钟",NULL,0);

    //
    // Initialization of 'Text'
    //


//    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
//    TEXT_SetTextAlign(hItem, GUI_TA_CENTER | GUI_TA_VCENTER);
//    TEXT_SetTextColor(hItem, UCLOR_RED);
//    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
//    TEXT_SetTextAlign(hItem, GUI_TA_CENTER | GUI_TA_VCENTER);
//    TEXT_SetTextColor(hItem, UCLOR_RED);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        WM_DeleteWindow(pMsg->hWin);
        ui_parameter();
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        WM_DeleteWindow(pMsg->hWin);
        ui_clock();
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;

    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       ui_main
*/

WM_HWIN ui_main(void);
WM_HWIN ui_main(void) {
  WM_HWIN hWin;


  printf("Create_data_record ==> mem : %d\r\n",GUI_ALLOC_GetNumFreeBytes());

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);	

  WM_CreateTimer(hWin, 0, 1000, 0);
  ui_main_hWin = hWin;
  data_set_lcd.inquire_ui_hWin = ui_main_hWin;
  return hWin;
  

}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
