/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#include "main.h"
#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_EDIT_0 (GUI_ID_USER + 0x02)
#define ID_TEXT_1 (GUI_ID_USER + 0x04)
#define ID_EDIT_1 (GUI_ID_USER + 0x05)
#define ID_TEXT_2 (GUI_ID_USER + 0x06)
#define ID_EDIT_2 (GUI_ID_USER + 0x07)
#define ID_BUTTON_0 (GUI_ID_USER + 0x08)
#define ID_BUTTON_1 (GUI_ID_USER + 0x09)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 320, 240, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_0, 5, 25, 150, 40, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 165, 25, 40, 40, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 215, 25, 40, 40, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 265, 25, 40, 40, 0, 0x64, 0 },
  
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 5, 75, 150, 40, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_2, 165, 75, 40, 40, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 225, 140, 80, 40, 0, 0x0, 10 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 225, 190, 80, 40, 0, 0x0, 10 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
WM_HWIN ui_parameter_hWin = NULL;
// USER START (Optionally insert additional static code)
// USER END
static void refresh_page()
{
    WM_HWIN hItem;
    char tmp_str[40] = {0};
    
    sprintf(tmp_str,"%d",data_set_lcd.start_time[0]);
    hItem = WM_GetDialogItem(ui_parameter_hWin, ID_EDIT_0);
    EDIT_SetText(hItem, tmp_str);
    EDIT_SetFont(hItem, &GUI_Font_micro_25);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    
    sprintf(tmp_str,"%d",data_set_lcd.start_time[1]);
    hItem = WM_GetDialogItem(ui_parameter_hWin, ID_EDIT_1);
    EDIT_SetText(hItem, tmp_str);
    EDIT_SetFont(hItem, &GUI_Font_micro_25);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    
    sprintf(tmp_str,"%d",data_set_lcd.arm_time);
    hItem = WM_GetDialogItem(ui_parameter_hWin, ID_EDIT_2);
    EDIT_SetText(hItem, tmp_str);
    EDIT_SetFont(hItem, &GUI_Font_micro_25);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    
    
    hItem = WM_GetDialogItem(ui_parameter_hWin, ID_TEXT_0);
    TEXT_SetText(hItem," 屏幕显示起(小时) "); // 
    TEXT_SetTextAlign(hItem, TEXT_CF_LEFT|TEXT_CF_VCENTER );
    TEXT_SetFont(hItem, &GUI_Font_micro_25);
    TEXT_SetBkColor(hItem,GUI_INVALID_COLOR);
    TEXT_SetTextColor(hItem,GUI_BLACK); 
    
    hItem = WM_GetDialogItem(ui_parameter_hWin, ID_TEXT_1);
    TEXT_SetText(hItem," 到 "); // 
    TEXT_SetTextAlign(hItem, TEXT_CF_HCENTER|TEXT_CF_VCENTER );
    TEXT_SetFont(hItem, &GUI_Font_micro_25);
    TEXT_SetBkColor(hItem,GUI_INVALID_COLOR);
    TEXT_SetTextColor(hItem,GUI_BLACK); 
    
    hItem = WM_GetDialogItem(ui_parameter_hWin, ID_TEXT_2);
    TEXT_SetText(hItem," 闹钟的间隔(分钟) "); // 
    TEXT_SetTextAlign(hItem, TEXT_CF_LEFT|TEXT_CF_VCENTER );
    TEXT_SetFont(hItem, &GUI_Font_micro_25);
    TEXT_SetBkColor(hItem,GUI_INVALID_COLOR);
    TEXT_SetTextColor(hItem,GUI_BLACK); 
}
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem,hWin= pMsg->hWin;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_PAINT:
//    GUI_SetBkColor(GUI_LIGHTYELLOW);
    refresh_page();
    if(data_set_lcd.start_time[0] < data_set_lcd.start_time[1]){
      uiWarning(hWin,WARN_RED_TEXT,"警告","设置超限!",0);
    }
    break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "123");
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "123");
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetText(hItem, "123");
    
    hItem= WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    button_user_skin_set(hItem,"确定",NULL,0);

    hItem= WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    button_user_skin_set(hItem,"返回",NULL,0);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        keypadEditInt(hWin,Id,0,23,&data_set_lcd.start_time[0]);
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        keypadEditInt(hWin,Id,0,23,&data_set_lcd.start_time[1]);
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        keypadEditInt(hWin,Id,0,59,&data_set_lcd.arm_time);
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        xQueueSend(ParaClockQue,( void * ) &data_set_lcd, 0);
        uiWarning(hWin,WARN_RED_TEXT,"提示","设置成功!",0);
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        WM_DeleteWindow(pMsg->hWin);
        ui_main();
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       ui_parameter
*/
WM_HWIN ui_parameter(void);
WM_HWIN ui_parameter(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  ui_parameter_hWin = hWin;
  data_set_lcd.inquire_ui_hWin = ui_parameter_hWin;
  data_set_lcd.time_en = 0;
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
